"""Build the OpenAPI `paths` map from the server-api/ folder tree.

The folder layout *is* the URL tree. Every `.yaml` file under `server-api/`
(other than `openapi.yaml`, the bundled output, and this script's own
generated file) is a PathItem, and its location determines its URL:

    a/b/c.yaml      ->  /a/b/c
    a/b/c/c.yaml    ->  /a/b/c     (index form: file named after its folder,
                                    used when the URL also has child routes)

Params are ordinary path segments, so they are just folder or file names::

    tools/{tool_name}/{tool_name}.yaml      ->  /tools/{tool_name}
    tools/{tool_name}/enable.yaml           ->  /tools/{tool_name}/enable
    tts/fetch/{response_id}.yaml            ->  /tts/fetch/{response_id}

The result is written to `server-api/_paths.generated.yaml`, a paths map of
`<url>: { $ref: ./<relative-file> }`. `openapi.yaml` pulls it in with a single
`paths: { $ref: ./_paths.generated.yaml }`, so adding an endpoint means
creating one file -- `openapi.yaml` never changes.

Run via `make build-api-docs` (or as part of `make docs-bundle`).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "server-api"
DEFAULT_OUTPUT = "_paths.generated.yaml"

# Files under the input dir that are not PathItems.
_NON_PATH_FILES = {"openapi.yaml", "openapi.bundled.yaml"}


def url_for(relative: Path) -> str:
    """Map a PathItem file (relative to the input dir) to its URL."""
    dirs = list(relative.parent.parts)
    stem = relative.stem
    # Index form: `foo/foo.yaml` is the endpoint for `/foo` itself (used when
    # `/foo` also has child routes that need `foo/` to exist as a folder).
    if dirs and stem == dirs[-1]:
        segments = dirs
    else:
        segments = dirs + [stem]
    return "/" + "/".join(segments)


def collect(input_dir: Path, output_name: str) -> dict[str, dict]:
    skip = _NON_PATH_FILES | {output_name}
    paths: dict[str, dict] = {}
    origin: dict[str, Path] = {}
    for path in sorted(input_dir.rglob("*.yaml")):
        if not path.is_file() or path.name in skip:
            continue
        relative = path.relative_to(input_dir)
        url = url_for(relative)
        if url in origin:
            raise SystemExit(
                f"Duplicate URL {url!r}: both {origin[url]} and {relative} map to it"
            )
        origin[url] = relative
        paths[url] = {"$ref": "./" + relative.as_posix()}
    return {url: paths[url] for url in sorted(paths)}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input", "-i", type=Path, default=DEFAULT_INPUT,
        help="Root directory of the split spec (default: server-api/)",
    )
    parser.add_argument(
        "--output", "-o", default=DEFAULT_OUTPUT,
        help="Generated paths file, relative to --input "
        f"(default: {DEFAULT_OUTPUT})",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    paths = collect(args.input, args.output)
    out = args.input / args.output
    with out.open("w") as fh:
        fh.write(
            f"# Auto-generated by scripts/{Path(__file__).name} from the\n"
            "# server-api/ folder tree. Do not edit by hand.\n"
        )
        yaml.safe_dump(paths, fh, sort_keys=False, default_flow_style=False)
    print(f"Wrote {out.relative_to(ROOT)} ({len(paths)} paths)")


if __name__ == "__main__":
    main()
