"""Build `server-api/tools/tools-module.yaml` from per-module paths fragments.

Each `server-api/tools/modules/<module>/<module>.yaml` is a paths fragment
keyed by URL suffix (relative to `/tools/<module>/module/`), e.g.::

    '': { $ref: ./<module>-details.yaml }
    schedules: { $ref: ./schedule-schedules.yaml }

This script collects every such fragment into a single paths-fragment file
at `server-api/tools/tools-module.yaml`, rewriting the sibling refs so they
resolve from the aggregator's directory. `openapi.yaml#/paths` references
the result via a sibling `$ref`, which Redocly merges into the top-level
paths map at bundle time.

Run via `make build-tools-module` (or as part of `make docs-bundle`).
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT / "server-api" / "tools"
MODULES_DIR = TOOLS_DIR / "modules"
OUT = TOOLS_DIR / "tools-module.yaml"


def collect() -> dict[str, dict]:
    paths: dict[str, dict] = {}
    for module_dir in sorted(MODULES_DIR.iterdir()):
        if not module_dir.is_dir():
            continue
        name = module_dir.name
        manifest_path = module_dir / f"{name}.yaml"
        if not manifest_path.exists():
            continue

        with manifest_path.open() as fh:
            manifest = yaml.safe_load(fh) or {}

        for suffix, entry in manifest.items():
            url = f"/tools/{name}/module/" if suffix == "" else f"/tools/{name}/module/{suffix}"
            paths[url] = _rewrite_refs(entry, name)
    return paths


def _rewrite_refs(node, module: str):
    """Rewrite `./X` refs (sibling of the module file) to be relative to
    `tools-module.yaml` (which sits one level above `modules/<module>/`).
    """
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k == "$ref" and isinstance(v, str) and v.startswith("./"):
                out[k] = f"./modules/{module}/{v[2:]}"
            else:
                out[k] = _rewrite_refs(v, module)
        return out
    if isinstance(node, list):
        return [_rewrite_refs(item, module) for item in node]
    return node


def main() -> None:
    paths = collect()
    with OUT.open("w") as fh:
        fh.write(
            "# Auto-generated by scripts/build_tools_module.py from\n"
            "# server-api/tools/modules/*/*.yaml. Do not edit by hand.\n"
        )
        yaml.safe_dump(paths, fh, sort_keys=False, default_flow_style=False)
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(paths)} paths)")


if __name__ == "__main__":
    main()
